In [1]:
import numpy as np
import pandas as pd
from glob import glob
import xml.etree.ElementTree as xet

import cv2

In [2]:
import os

In [3]:
df = pd.read_csv('labels.csv')
df.head()

            filepath  xmin  xmax  ymin  ymax
0  ./images/N107.xml   207   356   174   287
1  ./images/N113.xml    39   108   129   157
2   ./images/N62.xml   289   421   188   232
3   ./images/N89.xml   150   378   217   269
4   ./images/N88.xml   208   370    89   173

### Labels yolo
    center_x, center_y, width , height

In [4]:
# parsing
def parsing(path):
    parser = xet.parse(path).getroot()
    name = parser.find('filename').text
    filename = f'./images/{name}'

    # width and height
    parser_size = parser.find('size')
    width = int(parser_size.find('width').text)
    height = int(parser_size.find('height').text)
    
    return filename, width, height
df[['filename','width','height']] = df['filepath'].apply(parsing).apply(pd.Series)

In [5]:
df.head()

,filepath,xmin,xmax,ymin,ymax,filename,width,height
0,./images/N107.xml,207,356,174,287,./images/N107.jpeg,441,363
1,./images/N113.xml,39,108,129,157,./images/N113.jpeg,400,300
2,./images/N62.xml,289,421,188,232,./images/N62.jpeg,500,269
3,./images/N89.xml,150,378,217,269,./images/N89.jpeg,500,393
4,./images/N88.xml,208,370,89,173,./images/N88.jpeg,610,338

In [6]:
# center_x, center_y, width , height
df['center_x'] = (df['xmax'] + df['xmin'])/(2*df['width'])
df['center_y'] = (df['ymax'] + df['ymin'])/(2*df['height'])

df['bb_width'] = (df['xmax'] - df['xmin'])/df['width']
df['bb_height'] = (df['ymax'] - df['ymin'])/df['height']

In [7]:
df.head()

,filepath,xmin,xmax,ymin,ymax,filename,width,height,center_x,center_y,bb_width,bb_height
0,./images/N107.xml,207,356,174,287,./images/N107.jpeg,441,363,0.638322,0.634986,0.337868,0.311295
1,./images/N113.xml,39,108,129,157,./images/N113.jpeg,400,300,0.183750,0.476667,0.172500,0.093333
2,./images/N62.xml,289,421,188,232,./images/N62.jpeg,500,269,0.710000,0.780669,0.264000,0.163569
3,./images/N89.xml,150,378,217,269,./images/N89.jpeg,500,393,0.528000,0.618321,0.456000,0.132316
4,./images/N88.xml,208,370,89,173,./images/N88.jpeg,610,338,0.473770,0.387574,0.265574,0.248521

In [8]:
### splittiamo i dati in train e test
df_train = df.iloc[:200]
df_test = df.iloc[200:]

text.file

    class_id, center_x, center_y, bb_width, bb_height

In [9]:
from shutil import copy

In [10]:
train_folder = './data_images/train'

values = df_train[['filename','center_x','center_y','bb_width','bb_height']].values
for fname, x,y, w, h in values:
    image_name = os.path.split(fname)[-1]
    txt_name = os.path.splitext(image_name)[0]
    
    dst_image_path = os.path.join(train_folder,image_name)
    dst_label_file = os.path.join(train_folder,txt_name+'.txt')
    
    # copiamo ogni immagine nella cartella
    copy(fname,dst_image_path)

    # generiamo file .txt che hanno le informazioni sull'etichetta
    label_txt = f'0 {x} {y} {w} {h}'
    with open(dst_label_file,mode='w') as f:
        f.write(label_txt)
        
        f.close()

In [11]:
test_folder = './data_images/test'

values = df_test[['filename','center_x','center_y','bb_width','bb_height']].values
for fname, x,y, w, h in values:
    image_name = os.path.split(fname)[-1]
    txt_name = os.path.splitext(image_name)[0]
    
    dst_image_path = os.path.join(test_folder,image_name)
    dst_label_file = os.path.join(test_folder,txt_name+'.txt')
    
    # copiamo ogni immagine nella cartella
    copy(fname,dst_image_path)

    # generiamo file .txt che hanno le informazioni sull'etichetta
    label_txt = f'0 {x} {y} {w} {h}'
    with open(dst_label_file,mode='w') as f:
        f.write(label_txt)
        
        f.close()

---